#include "../core/axton.h"

void registerstdlib(environment *env);
void registermathlib(environment *env);
void registervectorlib(environment *env);
void registergraphicslib(environment *env);
void registerengine3dlib(environment *env);
void registerdatetime(environment *env);
void registerhashlib(environment *env);
void registersubprocess(environment *env);
void registersocket(environment *env);
void registerre(environment *env);
void registerjson(environment *env);
void registercsv(environment *env);
void registertempfile(environment *env);
void registerlogging(environment *env);
void registerargparse(environment *env);
void registersecrets(environment *env);
void registerglob(environment *env);
void registerfnmatch(environment *env);
void registerpprint(environment *env);
void registercopy(environment *env);
void registeritertools(environment *env);
void registercollections(environment *env);
void registeros(environment *env);
void registersys(environment *env);
void registerthreading(environment *env);
void registerhttplib(environment *env);
void registerwebsocketlib(environment *env);
void registertunnellib(environment *env);
void registerguilib(environment *env);
void registerwebviewlib(environment *env);
void registerdblib(environment *env);
void registerpathlib(environment *env);
void registerasynclib(environment *env);
void registermetaprogramlib(environment *env);
void registergeneratorlib(environment *env);
void registercontextlib(environment *env);
void registerpipetransformlib(environment *env);
void registerpatternlib(environment *env);
void registerjwtlib(environment *env);
void registerauthlib(environment *env);
void registerencryptionlib(environment *env);
void registerenvlib(environment *env);
void registersecretlib(environment *env);
void registerauditlib(environment *env);
void registercolorlib(environment *env);
void registerdebuglib(environment *env);
void registerobfuscatelib(environment *env);
void registerailib(environment *env);
void registerextensionlib(environment *env);
void registerwebrtclib(environment *env);
void registerwebgpulib(environment *env);
void registercloudlib(environment *env);
void registercontainerlib(environment *env);
void registerenumlib(environment *env);
void registerdataclasslib(environment *env);
void registerunionlib(environment *env);
void registeroptionallib(environment *env);
void registergraphqllib(environment *env);
void registerunicodelib(environment *env);
void register3dlib(environment *env);
void registermemorylib(environment *env);
void registerweblib(environment *env);
void registerpackagelib(environment *env);
void registersecuritylib(environment *env);
void registerscriptlib(environment *env);
void registerosintlib(environment *env);
void registervisionlib(environment *env);
void registerocrlib(environment *env);
void registerprocesslib(environment *env);
void registeroverlaylib(environment *env);
void registerinputlib(environment *env);
void registerphysicslib(environment *env);
void registerecslib(environment *env);
void registeranimationlib(environment *env);
void registeraudiolib(environment *env);

void registeralllibs(environment *env) {
    registerstdlib(env);
    registermathlib(env);
    registervectorlib(env);
    registergraphicslib(env);
    registerengine3dlib(env);
    registerdatetime(env);
    registerhashlib(env);
    registersubprocess(env);
    registersocket(env);
    registerre(env);
    registerjson(env);
    registercsv(env);
    registertempfile(env);
    registerlogging(env);
    registerargparse(env);
    registersecrets(env);
    registerglob(env);
    registerfnmatch(env);
    registerpprint(env);
    registercopy(env);
    registeritertools(env);
    registercollections(env);
    registeros(env);
    registersys(env);
    registerthreading(env);
    registerhttplib(env);
    registerwebsocketlib(env);
    registertunnellib(env);
    registerguilib(env);
    registerwebviewlib(env);
    registerdblib(env);
    registerpathlib(env);
    registerasynclib(env);
    registermetaprogramlib(env);
    registergeneratorlib(env);
    registercontextlib(env);
    registerpipetransformlib(env);
    registerpatternlib(env);
    registerjwtlib(env);
    registerauthlib(env);
    registerencryptionlib(env);
    registerenvlib(env);
    registersecretlib(env);
    registerauditlib(env);
    registercolorlib(env);
    registerdebuglib(env);
    registerobfuscatelib(env);
    registerailib(env);
    registerextensionlib(env);
    registerwebrtclib(env);
    registerwebgpulib(env);
    registercloudlib(env);
    registercontainerlib(env);
    registerenumlib(env);
    registerdataclasslib(env);
    registerunionlib(env);
    registeroptionallib(env);
    registergraphqllib(env);
    registerunicodelib(env);
    register3dlib(env);
    registermemorylib(env);
    registerweblib(env);
    registerpackagelib(env);
    registersecuritylib(env);
    registerscriptlib(env);
    registerosintlib(env);
    registervisionlib(env);
    registerocrlib(env);
    registerprocesslib(env);
    registeroverlaylib(env);
    registerinputlib(env);
    registerphysicslib(env);
    registerecslib(env);
    registeranimationlib(env);
    registeraudiolib(env);
}
