#include "../core/axton.h"

void registerstdlib(environment *env);
void registermathlib(environment *env);
void registervectorlib(environment *env);
void registergraphicslib(environment *env);
void registerengine3dlib(environment *env);
void registerdatetime(environment *env);
void registerhashlib(environment *env);
void registersubprocess(environment *env);
void registersocket(environment *env);
void registerre(environment *env);
void registerjson(environment *env);
void registercsv(environment *env);
void registertempfile(environment *env);
void registerlogging(environment *env);
void registerargparse(environment *env);
void registersecrets(environment *env);
void registerglob(environment *env);
void registerfnmatch(environment *env);
void registerpprint(environment *env);
void registercopy(environment *env);
void registeritertools(environment *env);
void registercollections(environment *env);
void registeros(environment *env);
void registersys(environment *env);
void registerthreading(environment *env);
void registerhttplib(environment *env);
void registerwebsocketlib(environment *env);
void registertunnellib(environment *env);
void registerguilib(environment *env);
void registerwebviewlib(environment *env);
void registerdblib(environment *env);
void registerpathlib(environment *env);
void registerasynclib(environment *env);
void registermetaprogramlib(environment *env);
void registergeneratorlib(environment *env);
void registercontextlib(environment *env);
void registerpipetransformlib(environment *env);
void registerpatternlib(environment *env);
void registerjwtlib(environment *env);
void registerauthlib(environment *env);
void registerencryptionlib(environment *env);
void registerenvlib(environment *env);
void registersecretlib(environment *env);
void registerauditlib(environment *env);
void registercolorlib(environment *env);
void registerdebuglib(environment *env);
void registerobfuscatelib(environment *env);
void registerailib(environment *env);
void registerextensionlib(environment *env);
void registerwebrtclib(environment *env);
void registerwebgpulib(environment *env);
void registercloudlib(environment *env);
void registercontainerlib(environment *env);
void registerenumlib(environment *env);
void registerdataclasslib(environment *env);
void registerunionlib(environment *env);
void registeroptionallib(environment *env);
void registergraphqllib(environment *env);
void registerunicodelib(environment *env);
void register3dlib(environment *env);
void registermemorylib(environment *env);
void registerweblib(environment *env);
void registerpackagelib(environment *env);
void registersecuritylib(environment *env);
void registerscriptlib(environment *env);
void registerosintlib(environment *env);
void registervisionlib(environment *env);
void registerocrlib(environment *env);
void registerprocesslib(environment *env);
void registeroverlaylib(environment *env);
void registerinputlib(environment *env);
void registerphysicslib(environment *env);
void registerecslib(environment *env);
void registeranimationlib(environment *env);
void registeraudiolib(environment *env);
void registerrenderlib(environment *env);
void registerphysicsextralib(environment *env);
void registernetworklib(environment *env);
void registerassetlib(environment *env);
void registerframedebuglib(environment *env);
void registerperfproflib(environment *env);
void registerbuildsyslib(environment *env);
void registerassetpip elib(environment *env);
void registerfluidlib(environment *env);
void registeriklib(environment *env);
void registermorphlib(environment *env);
void registerhotreloadlib(environment *env);
void registervolfoglib(environment *env);
void registermotionblurlib(environment *env);
void registerantialiaslib(environment *env);
void registerinstancinglib(environment *env);
void registerlodlib(environment *env);
void registerfrustumlib(environment *env);
void registerocclusionlib(environment *env);
void registergpuparticleslib(environment *env);
void registercompoundlib(environment *env);
void registerterrainphyslib(environment *env);
void registerbuoyancylib(environment *env);
void registerwindlib(environment *env);
void registerexplosionlib(environment *env);
void registersurfacedetaillib(environment *env);
void registergilibrary(environment *env);
void registeranimretargetlib(environment *env);
void registerrootmotionlib(environment *env);
void registeranimeventlib(environment *env);
void registerprocanimlib(environment *env);
void registermocaplib(environment *env);
void registeranimcomplib(environment *env);
void registeraudioocclib(environment *env);
void registeraudiostrelib(environment *env);
void registeraudiomixlib(environment *env);
void registeraudiofxlib(environment *env);
void registerspatialaudiolib(environment *env);
void registermidilib(environment *env);
void registergesturelib(environment *env);
void registervoiceinlib(environment *env);
void registermultitouchlib(environment *env);
void registervrctrllib(environment *env);
void registerhapticlib(environment *env);
void registerlagcomplib(environment *env);
void registerpredictlib(environment *env);
void registerinterplib(environment *env);
void registerreplicationlib(environment *env);
void registernatlib(environment *env);
void registermatchmakinglib(environment *env);
void registerlobbieslib(environment *env);
void registervoicechatlib(environment *env);
void registercloudsavelib(environment *env);
void registersteamlib(environment *env);
void registerepiclib(environment *env);
void registergoaplib(environment *env);
void registermctslib(environment *env);
void registerrllib(environment *env);
void registerperceptionlib(environment *env);
void registerteamailib(environment *env);
void registerfuzzylib(environment *env);
void registerutilityailib(environment *env);
void registermateditorlib(environment *env);
void registershadeditorlib(environment *env);
void registeranimateditorlib(environment *env);
void registerprefablib(environment *env);
void registerseencelib(environment *env);
void registerterraineditlib(environment *env);
void registerparteditlib(environment *env);
void registeruieditlib(environment *env);
void registermemproflib(environment *env);
void registerassetbrowserlib(environment *env);
void registerconsolelib(environment *env);
void registerscriptdebuglib(environment *env);
void registervclib(environment *env);
void registersteampublib(environment *env);
void registeritchiolib(environment *env);
void registerepicstorelib(environment *env);
void registerpslib(environment *env);
void registerxboxlib(environment *env);
void registernintendolib(environment *env);
void registermobilelib(environment *env);
void registeranalyticslib(environment *env);
void registercrashlib(environment *env);
void registerachievementslib(environment *env);
void registerleaderboardslib(environment *env);
void registeriaplib(environment *env);
void registerantipiracylib(environment *env);
void registerdr mlib(environment *env);
void registerobjectpoollib(environment *env);
void registereventsyslib(environment *env);
void registerserviceloclib(environment *env);
void registerdilib(environment *env);
void registercoroutinelib(environment *env);
void registertimerlib(environment *env);
void registerwebrtclib(environment *env);
void registerwsclientlib(environment *env);
void registerssllib(environment *env);
void registerrenderdoclib(environment *env);
void registerimguilib(environment *env);
void registergltflib(environment *env);
void registerphysdebuglib(environment *env);
void registeraudiomixerlib(environment *env);
void registervideolib(environment *env);
void registerunicodelib(environment *env);
void registerlsplib(environment *env);
void registerlinterlib(environment *env);

void registeralllibs(environment *env) {
    registerstdlib(env);
    registermathlib(env);
    registervectorlib(env);
    registergraphicslib(env);
    registerengine3dlib(env);
    registerdatetime(env);
    registerhashlib(env);
    registersubprocess(env);
    registersocket(env);
    registerre(env);
    registerjson(env);
    registercsv(env);
    registertempfile(env);
    registerlogging(env);
    registerargparse(env);
    registersecrets(env);
    registerglob(env);
    registerfnmatch(env);
    registerpprint(env);
    registercopy(env);
    registeritertools(env);
    registercollections(env);
    registeros(env);
    registersys(env);
    registerthreading(env);
    registerhttplib(env);
    registerwebsocketlib(env);
    registertunnellib(env);
    registerguilib(env);
    registerwebviewlib(env);
    registerdblib(env);
    registerpathlib(env);
    registerasynclib(env);
    registermetaprogramlib(env);
    registergeneratorlib(env);
    registercontextlib(env);
    registerpipetransformlib(env);
    registerpatternlib(env);
    registerjwtlib(env);
    registerauthlib(env);
    registerencryptionlib(env);
    registerenvlib(env);
    registersecretlib(env);
    registerauditlib(env);
    registercolorlib(env);
    registerdebuglib(env);
    registerobfuscatelib(env);
    registerailib(env);
    registerextensionlib(env);
    registerwebrtclib(env);
    registerwebgpulib(env);
    registercloudlib(env);
    registercontainerlib(env);
    registerenumlib(env);
    registerdataclasslib(env);
    registerunionlib(env);
    registeroptionallib(env);
    registergraphqllib(env);
    registerunicodelib(env);
    register3dlib(env);
    registermemorylib(env);
    registerweblib(env);
    registerpackagelib(env);
    registersecuritylib(env);
    registerscriptlib(env);
    registerosintlib(env);
    registervisionlib(env);
    registerocrlib(env);
    registerprocesslib(env);
    registeroverlaylib(env);
    registerinputlib(env);
    registerphysicslib(env);
    registerecslib(env);
    registeranimationlib(env);
    registeraudiolib(env);
    registerrenderlib(env);
    registerphysicsextralib(env);
    registernetworklib(env);
    registerassetlib(env);
    registerframedebuglib(env);
    registerperfproflib(env);
    registerbuildsyslib(env);
    registerassetpip elib(env);
    registerfluidlib(env);
    registeriklib(env);
    registermorphlib(env);
    registerhotreloadlib(env);
    registervolfoglib(env);
    registermotionblurlib(env);
    registerantialiaslib(env);
    registerinstancinglib(env);
    registerlodlib(env);
    registerfrustumlib(env);
    registerocclusionlib(env);
    registergpuparticleslib(env);
    registercompoundlib(env);
    registerterrainphyslib(env);
    registerbuoyancylib(env);
    registerwindlib(env);
    registerexplosionlib(env);
    registersurfacedetaillib(env);
    registergilibrary(env);
    registeranimretargetlib(env);
    registerrootmotionlib(env);
    registeranimeventlib(env);
    registerprocanimlib(env);
    registermocaplib(env);
    registeranimcomplib(env);
    registeraudioocclib(env);
    registeraudiostrelib(env);
    registeraudiomixlib(env);
    registeraudiofxlib(env);
    registerspatialaudiolib(env);
    registermidilib(env);
    registergesturelib(env);
    registervoiceinlib(env);
    registermultitouchlib(env);
    registervrctrllib(env);
    registerhapticlib(env);
    registerlagcomplib(env);
    registerpredictlib(env);
    registerinterplib(env);
    registerreplicationlib(env);
    registernatlib(env);
    registermatchmakinglib(env);
    registerlobbieslib(env);
    registervoicechatlib(env);
    registercloudsavelib(env);
    registersteamlib(env);
    registerepiclib(env);
    registergoaplib(env);
    registermctslib(env);
    registerrllib(env);
    registerperceptionlib(env);
    registerteamailib(env);
    registerfuzzylib(env);
    registerutilityailib(env);
    registermateditorlib(env);
    registershadeditorlib(env);
    registeranimateditorlib(env);
    registerprefablib(env);
    registerseencelib(env);
    registerterraineditlib(env);
    registerparteditlib(env);
    registeruieditlib(env);
    registermemproflib(env);
    registerassetbrowserlib(env);
    registerconsolelib(env);
    registerscriptdebuglib(env);
    registervclib(env);
    registersteampublib(env);
    registeritchiolib(env);
    registerepicstorelib(env);
    registerpslib(env);
    registerxboxlib(env);
    registernintendolib(env);
    registermobilelib(env);
    registeranalyticslib(env);
    registercrashlib(env);
    registerachievementslib(env);
    registerleaderboardslib(env);
    registeriaplib(env);
    registerantipiracylib(env);
    registerdr mlib(env);
    registerobjectpoollib(env);
    registereventsyslib(env);
    registerserviceloclib(env);
    registerdilib(env);
    registercoroutinelib(env);
    registertimerlib(env);
    registerwebrtclib(env);
    registerwsclientlib(env);
    registerssllib(env);
    registerrenderdoclib(env);
    registerimguilib(env);
    registergltflib(env);
    registerphysdebuglib(env);
    registeraudiomixerlib(env);
    registervideolib(env);
    registerunicodelib(env);
    registerlsplib(env);
    registerlinterlib(env);
}
